package com.services.error.handler.tasks;

import com.services.error.handler.exceptions.BaseException;
import com.services.error.handler.responses.ErrorResponse;

/**
 * A task contract that can be used to define various tasks
 * that are required to be executed in case of exception scenarios.
 *
 * @author shashankmittal
 * @created 25/02/20
 */
public interface ITask {

    /**
     * Execute a given task logic using the information in the params.
     *
     * @param errorResponse Error Response generated by {@link com.services.error.handler.handlers.IExceptionHandler}.
     * @param e             Object of child class of {@link BaseException} generated by {@link com.services.error.handler.processors.IExceptionProcessor}.
     */
    void execute(ErrorResponse<?> errorResponse, BaseException e);
}
